spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true